// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTU9wXSmiuMIJP7cdC_OG8lZRDVicgxtA',
    appId: '1:721859996873:web:e4fc70f9eb8ad18578f118',
    messagingSenderId: '721859996873',
    projectId: 'livelearn-69eb6',
    authDomain: 'livelearn-69eb6.firebaseapp.com',
    storageBucket: 'livelearn-69eb6.appspot.com',
    measurementId: 'G-M8RDHZQ3KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwD_GuUSnKKaato5dbjn1Gq-r0gpMxS8',
    appId: '1:721859996873:android:fee5f6faaa160d2278f118',
    messagingSenderId: '721859996873',
    projectId: 'livelearn-69eb6',
    storageBucket: 'livelearn-69eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktlDRmQvQO1gusXpf7FU5wW_YRQ2w6Z4',
    appId: '1:721859996873:ios:6b5caa2001194b6d78f118',
    messagingSenderId: '721859996873',
    projectId: 'livelearn-69eb6',
    storageBucket: 'livelearn-69eb6.appspot.com',
    iosClientId: '721859996873-eopip54i2op2j108fiaged4jh4tc1fat.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCktlDRmQvQO1gusXpf7FU5wW_YRQ2w6Z4',
    appId: '1:721859996873:ios:c0a4f33cabd0035678f118',
    messagingSenderId: '721859996873',
    projectId: 'livelearn-69eb6',
    storageBucket: 'livelearn-69eb6.appspot.com',
    iosClientId: '721859996873-hvtrou2r6fq67k2eprha4ivodjj846f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing.RunnerTests',
  );
}
